### PR TITLE
Fixed for GNL 3.4

### PR DESCRIPTION
**Pull request by theknut**
Its confirmed working for Auto voice. I didn't test it myself, though. Definitely needs more testing!

### CODE REVIEW

**Comment by theknut** [comment]
Sweet! Glad I could contribute!
Am 02.06.2014 22:44 schrieb "Mohammad Abu-Garbeyyeh" <
notifications@github.com>:

**Comment by MohammadAG** [comment]
Just a question, which version of Google Search did you do this on? Any app that uses the voice API will crash because method "a" doesn't exist in mine :)

**Comment by MohammadAG** [comment]
BTW, I've pushed this to the repo as a beta apk, feel free to point users to that to ease signature mismatches.

**Comment by theknut** [comment]
I used GNL 3.4.16. A fellow tested it for me, should be the same version as
it is the latest. He said it's working with auto voice. Maybe you can try
and find a yourself. Which class is it? Maybe I'll look into it again, but
I can't test it.
Am 02.06.2014 23:06 schrieb "Mohammad Abu-Garbeyyeh" <
notifications@github.com>:

**Comment by theknut** [comment]
And using which plug in made it cause an exception?
Am 02.06.2014 23:08 schrieb "Alexander Schulz" <
alexander.as.schulz@gmail.com>:

**Comment by MohammadAG** [comment]
Voice Toggles, and someone PM'd be about this once so there are other plugins using it.
Fixed in latest commit, I also have a fallback in case the method isn't found, reduces the need to update these parts.

**Comment by theknut** [comment]
Can't see the commit but I see the repo version. So we pretty much got that
module rescued? That's awesome!
Am 02.06.2014 23:35 schrieb "Mohammad Abu-Garbeyyeh" <
notifications@github.com>:

**Comment by MohammadAG** [comment]
Hmm, git push --tags only pushes tags, that's new...
Anyway, here it is:
https://github.com/MohammadAG/Google-Search-API/commit/86d4fffa07ab60174f1c6012613807be66e2aeb2

Yeah, I didn't do any real work here, so thanks :D

**Pull request merged**
